### ISSUE TITLE
Not installable with `go get`

### ISSUE THREAD

**Issue by piranha** [edsrzf/tnetstring-go#2]
I don't understand why, but `-go` part makes this package non-installable with `go get`:

`> go get -x -v github.com/edsrzf/tnetstring-go
WORK=/var/folders/3d/1j2kw66x3g3g5syddr8w8c840000gn/T/go-build430912744`

While everything else just works:

```piranha@gto ~/var/gopath/src/fstore> go get -x -v github.com/edsrzf/tnetstring-g  
github.com/edsrzf/tnetstring-g (download)
^C
piranha@gto ~/var/gopath/src/fstore> go get -x -v github.com/edsrzf/tnetstring.go
github.com/edsrzf/tnetstring.go (download)
^C
piranha@gto ~/var/gopath/src/fstore> go get -x -v github.com/edsrzf/tnetstringgo 
github.com/edsrzf/tnetstringgo (download)
^C

```

I don't understand what's the problem, but it would be nice to fix it.
```

**Comment by edsrzf** [comment]
Works fine for me. Make sure you delete the package file under $GOPATH/pkg/$GOOS_$GOARCH/github.com/edsrzf/tnetstring-go.a. Otherwise the go tool thinks the package is already installed.

**Comment by sansolovyov** [comment]
Hm, sorry, I've updated go and it started to work. Not sure what exactly happened.
